/* eslint-disable no-unused-vars */
import { useState } from "react";
import { AuthNav } from "../ui/AuthNav";
import { ProfileUpdateModal } from "../dashboard/ProfileUpdateModal";
import {
  ArrowLeft,
  Download,
  Copy,
  Check,
  Share2,
  ShoppingCart,
  ChevronDown,
  CheckCircle,
  AlertCircle,
  Flag,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

// Constants
const TABS = {
  BEST: "best",
  BUDGET: "budget",
  NATURAL: "natural",
  LOCAL: "local",
};

const TAB_CONFIG = [
  { id: TABS.BEST, label: "Best Matches" },
  { id: TABS.BUDGET, label: "Budget Options" },
  { id: TABS.NATURAL, label: "Natural/Organic" },
  { id: TABS.LOCAL, label: "Local Brands" },
];

const SEVERITY_STYLES = {
  Moderate: "bg-yellow-100 text-yellow-800",
  Mild: "bg-green-100 text-green-800",
  Severe: "bg-red-100 text-red-800",
};

const CLIPBOARD_RESET_DELAY = 3000;

// Services
const ClipboardService = {
  copyText: async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (error) {
      console.error("Copy failed:", error);
      return false;
    }
  },

  copyWithImage: async (imageUrl, text) => {
    if (!navigator.clipboard || typeof ClipboardItem === "undefined") {
      return await ClipboardService.copyText(text);
    }

    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();

      const clipboardItem = new ClipboardItem({
        [blob.type]: blob,
        "text/plain": new Blob([text], { type: "text/plain" }),
      });

      await navigator.clipboard.write([clipboardItem]);
      return true;
    } catch (error) {
      console.log("Image copy failed, falling back to text only");
      return await ClipboardService.copyText(text);
    }
  },
};

const ShareService = {
  canShare: () => typeof navigator.share !== "undefined",

  shareWithImage: async (imageUrl, title, text) => {
    if (!ShareService.canShare()) {
      return false;
    }

    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const file = new File([blob], "my-skin-analysis.jpg", {
        type: blob.type,
      });

      await navigator.share({
        title,
        text,
        files: [file],
      });

      return true;
    } catch (error) {
      console.log("Share with image failed:", error);
      return await ShareService.shareText(title, text);
    }
  },

  shareText: async (title, text) => {
    if (!ShareService.canShare()) {
      return false;
    }

    try {
      await navigator.share({ title, text });
      return true;
    } catch (error) {
      console.error("Share failed:", error);
      return false;
    }
  },
};

const DownloadService = {
  downloadText: (content, filename) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },
};

const FormatService = {
  formatDate: (date) => {
    return date.toLocaleDateString("en-NG", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
  },

  formatResultsSummary: (results, products) => {
    return `DermAI Skin Analysis Results
Analyzed: ${FormatService.formatDate(new Date())}

Skin Type: ${results.skinType} (${results.confidence}% confidence)

Identified Conditions:
${results.conditions.map((c) => `- ${c.name}: ${c.severity} (${c.confidence}% confidence)`).join("\n")}

Top Product Recommendations:
${products
  .slice(0, 3)
  .map(
    (p, i) =>
      `${i + 1}. ${p.name} by ${p.brand} - ${p.price} (Match: ${p.score}%)`,
  )
  .join("\n")}

Generated by DermAI - Your AI-Powered Skincare Assistant`;
  },

  formatDetailedResults: (results, products, imageUrl) => {
    return `DermAI Skin Analysis Results
=================================
Analyzed: ${FormatService.formatDate(new Date())}

SKIN TYPE: ${results.skinType}
Confidence: ${results.confidence}%

IDENTIFIED CONDITIONS:
${results.conditions.map((c) => `• ${c.name}: ${c.severity} (${c.confidence}% confidence)`).join("\n")}

TOP PRODUCT RECOMMENDATIONS:
${products
  .slice(0, 5)
  .map(
    (p, i) => `
${i + 1}. ${p.name}
   Brand: ${p.brand}
   Price: ${p.price}
   Match Score: ${p.score}%
   ${p.whyRecommended ? `Why: ${p.whyRecommended.join(", ")}` : ""}`,
  )
  .join("\n")}

IMAGE URL: ${imageUrl}

=================================
Generated by DermAI
Your AI-Powered Skincare Assistant for Nigerian Consumers
Visit: https://dermai.app`;
  },

  formatShareText: (results, products) => {
    return `Check out my DermAI skin analysis results!\n\nSkin Type: ${results.skinType} (${results.confidence}% confident)\n\nTop Recommendations:\n${products
      .slice(0, 2)
      .map((p) => `• ${p.name} by ${p.brand}`)
      .join("\n")}\n\nGet your personalized skincare routine at DermAI!`;
  },
};

// Mock Data
const getMockAnalysisResults = () => ({
  skinType: "Combination",
  confidence: 92,
  conditions: [
    { name: "Hyperpigmentation", severity: "Moderate", confidence: 88 },
    { name: "Dehydration", severity: "Mild", confidence: 85 },
    { name: "Uneven Texture", severity: "Mild", confidence: 78 },
  ],
  uploadedImage:
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
});

const getMockProducts = () => ({
  best: [
    {
      id: 1,
      name: "CeraVe Hydrating Facial Cleanser",
      brand: "CeraVe",
      price: "₦8,500",
      score: 98,
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=300",
      available: true,
      whyRecommended: [
        "Contains Hyaluronic Acid for hydration",
        "Non-comedogenic formula",
        "pH-balanced for combination skin",
        "Fragrance-free",
      ],
      category: "Cleanser",
    },
    {
      id: 2,
      name: "The Ordinary Niacinamide 10% + Zinc 1%",
      brand: "The Ordinary",
      price: "₦6,200",
      score: 96,
      image:
        "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300",
      available: true,
      whyRecommended: [
        "Targets hyperpigmentation",
        "Controls oil production",
        "Minimizes pores",
        "Budget-friendly",
      ],
      category: "Treatment",
    },
    {
      id: 3,
      name: "Neutrogena Hydro Boost Water Gel",
      brand: "Neutrogena",
      price: "₦12,000",
      score: 94,
      image:
        "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=300",
      available: true,
      whyRecommended: [
        "Lightweight gel texture",
        "Hyaluronic acid boosts hydration",
        "Oil-free formula",
        "Absorbs quickly",
      ],
      category: "Moisturizer",
    },
    {
      id: 4,
      name: "La Roche-Posay Anthelios SPF 50+",
      brand: "La Roche-Posay",
      price: "₦15,500",
      score: 92,
      image:
        "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=300",
      available: true,
      whyRecommended: [
        "Broad spectrum protection",
        "No white cast on dark skin",
        "Matte finish",
        "Prevents further pigmentation",
      ],
      category: "Sunscreen",
    },
    {
      id: 5,
      name: "Paula's Choice 2% BHA Liquid Exfoliant",
      brand: "Paula's Choice",
      price: "₦18,000",
      score: 90,
      image:
        "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=300",
      available: false,
      whyRecommended: [
        "Exfoliates dead skin cells",
        "Unclogs pores",
        "Evens skin texture",
        "Gentle for daily use",
      ],
      category: "Treatment",
    },
  ],
  budget: [
    {
      id: 6,
      name: "Simple Kind to Skin Refreshing Facial Wash",
      brand: "Simple",
      price: "₦3,500",
      score: 85,
      image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=300",
      available: true,
      value: "Best Value",
      category: "Cleanser",
    },
    {
      id: 7,
      name: "Nivea Daily Essentials Light Moisturiser",
      brand: "Nivea",
      price: "₦2,800",
      score: 82,
      image:
        "https://images.unsplash.com/photo-1590393876825-1c0bd1a5ef77?w=300",
      available: true,
      value: "Most Affordable",
      category: "Moisturizer",
    },
  ],
  natural: [
    {
      id: 8,
      name: "Shea Moisture African Black Soap",
      brand: "Shea Moisture",
      price: "₦7,500",
      score: 89,
      image:
        "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=300",
      available: true,
      certifications: ["Organic", "Cruelty-Free"],
      category: "Cleanser",
    },
  ],
  local: [
    {
      id: 9,
      name: "Oríkì Glow Serum",
      brand: "Oríkì Naturals",
      price: "₦9,000",
      score: 87,
      image:
        "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300",
      available: true,
      local: true,
      category: "Treatment",
    },
  ],
});

// Components
function ConditionCard({ condition }) {
  const severityStyle =
    SEVERITY_STYLES[condition.severity] || SEVERITY_STYLES.Mild;

  return (
    <div className="bg-[#f8f6f3] rounded-xl p-4">
      <div className="flex items-center justify-between mb-2">
        <span className="text-sm sm:text-base text-[#2a2420] font-light">
          {condition.name}
        </span>
        <span
          className={`text-xs px-2 py-1 rounded-full font-light ${severityStyle}`}
        >
          {condition.severity}
        </span>
      </div>
      <div className="flex items-center gap-2">
        <div className="flex-1 bg-white rounded-full h-1.5">
          <div
            className="bg-[#8b7355] rounded-full h-1.5 transition-all"
            style={{ width: `${condition.confidence}%` }}
          ></div>
        </div>
        <span className="text-xs text-[#5a5450] font-light">
          {condition.confidence}%
        </span>
      </div>
    </div>
  );
}

function SkinTypeCard({ skinType, confidence }) {
  return (
    <div className="bg-linear-to-br from-[#8b7355] to-[#6d5a43] rounded-2xl p-6 text-white mb-4">
      <h3 className="text-lg mb-2 font-light">Detected Skin Type</h3>
      <div className="flex items-end gap-3">
        <span className="text-3xl sm:text-4xl font-light">{skinType}</span>
        <span className="text-lg opacity-90 mb-1 font-light">
          {confidence}% confident
        </span>
      </div>
      <div className="mt-4 bg-white/20 rounded-full h-2">
        <div
          className="bg-white rounded-full h-2 transition-all"
          style={{ width: `${confidence}%` }}
        ></div>
      </div>
    </div>
  );
}

function ProductBadge({ type, label }) {
  const badges = {
    topPick: { style: "bg-yellow-100 text-yellow-800", icon: null },
    inStock: {
      style: "bg-green-100 text-green-800",
      icon: <CheckCircle size={12} />,
    },
    outOfStock: {
      style: "bg-red-100 text-red-800",
      icon: <AlertCircle size={12} />,
    },
    local: { style: "bg-blue-100 text-blue-800", icon: <Flag size={12} /> },
  };

  const badge = badges[type];
  if (!badge) return null;

  return (
    <span
      className={`text-xs px-2 py-0.5 rounded-full font-light flex items-center gap-1 ${badge.style}`}
    >
      {badge.icon}
      {label}
    </span>
  );
}

function ProductCard({ product, isFirst, onExpand, isExpanded }) {
  return (
    <div className="border-2 border-[#e8e6e3] rounded-2xl p-4 sm:p-6 hover:border-[#8b7355] transition-all">
      <div className="flex flex-col sm:flex-row gap-4">
        {/* Product Image */}
        <div className="w-full sm:w-24 lg:w-32 h-48 sm:h-24 lg:h-32 rounded-xl overflow-hidden bg-[#f8f6f3] flex-shrink-0">
          <img
            src={product.image}
            alt={product.name}
            className="w-full h-full object-cover"
          />
        </div>

        {/* Product Info */}
        <div className="flex-1 min-w-0">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 mb-3">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1 flex-wrap">
                <span className="text-xs text-[#5a5450] font-light">
                  {product.brand}
                </span>
                {isFirst && <ProductBadge type="topPick" label="Top Pick" />}
                <ProductBadge
                  type={product.available ? "inStock" : "outOfStock"}
                  label={product.available ? "In Stock" : "Out of Stock"}
                />
                {product.local && <ProductBadge type="local" label="Local" />}
              </div>
              <h3 className="text-base sm:text-lg text-[#2a2420] mb-1 font-light">
                {product.name}
              </h3>
              <div className="flex flex-wrap items-center gap-3">
                <span className="text-lg sm:text-xl text-[#8b7355] font-light">
                  {product.price}
                </span>
                <div className="flex items-center gap-2">
                  <span className="text-sm text-[#5a5450] font-light">
                    Match Score:
                  </span>
                  <span className="text-sm px-2 py-1 bg-[#8b7355] text-white rounded-lg font-light">
                    {product.score}%
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Why Recommended */}
          {product.whyRecommended && (
            <div className="mt-3">
              <button
                onClick={() => onExpand(product.id)}
                className="flex items-center gap-2 text-sm text-[#8b7355] hover:text-[#2a2420] transition-colors mb-2 font-light"
              >
                <ChevronDown
                  size={16}
                  className={`transition-transform ${isExpanded ? "rotate-180" : ""}`}
                />
                Why Recommended
              </button>

              {isExpanded && (
                <ul className="space-y-2 pl-6">
                  {product.whyRecommended.map((reason, i) => (
                    <li
                      key={i}
                      className="text-sm text-[#5a5450] font-light flex items-start gap-2"
                    >
                      <Check
                        size={16}
                        className="text-[#8b7355] mt-0.5 flex-shrink-0"
                      />
                      <span>{reason}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex flex-wrap gap-2 mt-4">
            <button className="px-4 py-2 bg-[#8b7355] text-white rounded-xl hover:bg-[#6d5a43] transition-all text-sm font-light">
              Save to Routine
            </button>
            <button className="px-4 py-2 border-2 border-[#e8e6e3] text-[#2a2420] rounded-xl hover:border-[#8b7355] transition-all text-sm font-light">
              Browse Similar
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function TabButton({ tab, isActive, onClick }) {
  return (
    <button
      onClick={onClick}
      className={`flex-1 sm:flex-none px-4 sm:px-6 py-4 text-sm sm:text-base whitespace-nowrap transition-colors font-light ${
        isActive
          ? "border-b-2 border-[#8b7355] text-[#2a2420] bg-[#f8f6f3]"
          : "text-[#5a5450] hover:text-[#2a2420]"
      }`}
    >
      {tab.label}
    </button>
  );
}

function ActionButton({
  onClick,
  icon: Icon,
  label,
  variant = "secondary",
  disabled = false,
}) {
  const baseClasses =
    "px-6 py-4 rounded-2xl transition-all flex items-center justify-center gap-2 font-light";
  const variantClasses =
    variant === "primary"
      ? "bg-[#8b7355] text-white hover:bg-[#6d5a43]"
      : "bg-white border-2 border-[#e8e6e3] hover:border-[#8b7355] text-[#2a2420]";

  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={`${baseClasses} ${variantClasses}`}
    >
      <Icon size={20} />
      {label}
    </button>
  );
}

// Main Component
export function ResultsPage() {
  const navigate = useNavigate();
  const [showProfileModal, setShowProfileModal] = useState(false);
  const [copiedToClipboard, setCopiedToClipboard] = useState(false);
  const [activeTab, setActiveTab] = useState(TABS.BEST);
  const [expandedProduct, setExpandedProduct] = useState(null);

  const mockUser = { name: "Amara Okafor" };
  const analysisResults = getMockAnalysisResults();
  const allProducts = getMockProducts();

  const getCurrentProducts = () => allProducts[activeTab] || allProducts.best;

  const handleCopyResults = async () => {
    const summary = FormatService.formatResultsSummary(
      analysisResults,
      allProducts.best,
    );
    const success = await ClipboardService.copyWithImage(
      analysisResults.uploadedImage,
      summary,
    );

    if (success) {
      setCopiedToClipboard(true);
      setTimeout(() => setCopiedToClipboard(false), CLIPBOARD_RESET_DELAY);
    } else {
      alert("Failed to copy results. Please try downloading instead.");
    }
  };

  const handleDownloadResults = () => {
    const content = FormatService.formatDetailedResults(
      analysisResults,
      allProducts.best,
      analysisResults.uploadedImage,
    );
    const filename = `dermai-analysis-${new Date().toISOString().split("T")[0]}.txt`;
    DownloadService.downloadText(content, filename);
  };

  const handleShareResults = async () => {
    const shareText = FormatService.formatShareText(
      analysisResults,
      allProducts.best,
    );
    const title = "My DermAI Skin Analysis";

    const shared = await ShareService.shareWithImage(
      analysisResults.uploadedImage,
      title,
      shareText,
    );

    if (!shared) {
      const copied = await ClipboardService.copyText(shareText);
      if (copied) {
        alert("Results copied to clipboard! You can paste them anywhere.");
      }
    }
  };

  const handleExpandProduct = (productId) => {
    setExpandedProduct(expandedProduct === productId ? null : productId);
  };

  const handleNavigate = (path) => {
    navigate(path);
  };

  return (
    <div className="min-h-screen bg-[#f8f6f3]">
      <ProfileUpdateModal
        isOpen={showProfileModal}
        onClose={() => setShowProfileModal(false)}
      />

      <AuthNav
        currentPage="dashboard"
        userName={mockUser.name}
        onUpdateProfile={() => setShowProfileModal(true)}
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8 pt-24 sm:pt-28">
        {/* Header */}
        <div className="mb-6">
          <button
            onClick={() => handleNavigate("/dashboard")}
            className="text-sm text-[#8b7355] hover:text-[#2a2420] transition-colors flex items-center gap-2 mb-4 font-light"
          >
            <ArrowLeft size={16} />
            Back to Dashboard
          </button>
          <h1 className="text-2xl sm:text-3xl lg:text-4xl text-[#2a2420] mb-2 font-light">
            Your Skin Analysis Results
          </h1>
          <p className="text-sm sm:text-base text-[#5a5450] font-light">
            Analyzed on {FormatService.formatDate(new Date())}
          </p>
        </div>

        {/* Analysis Summary */}
        <div className="bg-white rounded-3xl shadow-lg p-4 sm:p-6 lg:p-8 mb-6">
          <h2 className="text-xl sm:text-2xl text-[#2a2420] mb-6 font-light">
            Analysis Summary
          </h2>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
            {/* Uploaded Image */}
            <div className="rounded-2xl overflow-hidden bg-[#f8f6f3] aspect-square">
              <img
                src={analysisResults.uploadedImage}
                alt="Your skin"
                className="w-full h-full object-cover"
              />
            </div>

            {/* Detection Results */}
            <div>
              <SkinTypeCard
                skinType={analysisResults.skinType}
                confidence={analysisResults.confidence}
              />

              {/* Identified Conditions */}
              <div>
                <h3 className="text-lg text-[#2a2420] mb-3 font-light">
                  Identified Conditions
                </h3>
                <div className="space-y-3">
                  {analysisResults.conditions.map((condition, index) => (
                    <ConditionCard key={index} condition={condition} />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Recommendation Tabs */}
        <div className="bg-white rounded-3xl shadow-lg overflow-hidden">
          {/* Tab Headers */}
          <div className="border-b border-[#e8e6e3] overflow-x-auto">
            <div className="flex min-w-max sm:min-w-0">
              {TAB_CONFIG.map((tab) => (
                <TabButton
                  key={tab.id}
                  tab={tab}
                  isActive={activeTab === tab.id}
                  onClick={() => setActiveTab(tab.id)}
                />
              ))}
            </div>
          </div>

          {/* Tab Content */}
          <div className="p-4 sm:p-6 lg:p-8">
            <div className="space-y-4">
              {getCurrentProducts().map((product, index) => (
                <ProductCard
                  key={product.id}
                  product={product}
                  isFirst={activeTab === TABS.BEST && index === 0}
                  onExpand={handleExpandProduct}
                  isExpanded={expandedProduct === product.id}
                />
              ))}
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <ActionButton
            onClick={handleDownloadResults}
            icon={Download}
            label="Download Results"
          />
          <ActionButton
            onClick={handleCopyResults}
            icon={copiedToClipboard ? Check : Copy}
            label={copiedToClipboard ? "Copied!" : "Copy with Image"}
          />
          <ActionButton
            onClick={handleShareResults}
            icon={Share2}
            label="Share Results"
          />
          <ActionButton
            onClick={() => handleNavigate("/products")}
            icon={ShoppingCart}
            label="Browse All Products"
            variant="primary"
          />
        </div>
      </div>
    </div>
  );
}
